# Generated by Django 2.2.9 on 2019-12-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('práctica_05', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='origen',
            field=models.CharField(default='Londres', max_length=200),
            preserve_default=False,
        ),
    ]
